apiVersion: v1
kind: Service
metadata:
  name: frontend-lb
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: frontend
status: {}

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: santagar/kubernetes-solution-frontend
        imagePullPolicy: Always
        name: frontend
        ports:
        - containerPort: 80
status: {}

---

apiVersion: v1
kind: Service
metadata:
  name: frontend-api-lb
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: frontend-api
status: {}

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend-api
spec:
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: frontend-api
    spec:
      containers:
      - image: santagar/kubernetes-solution-frontend-api
        imagePullPolicy: Always
        name: frontend-api
        env:
        - name: MICROSERVICE_URL
          value: "http://microservice"
        ports:
        - containerPort: 8080
status: {}

---

apiVersion: v1
kind: Service
metadata:
  name: microservice
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: microservice
status: {}

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: microservice
spec:
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: microservice
    spec:
      containers:
      - image: santagar/kubernetes-solution-microservice
        imagePullPolicy: Always
        name: microservice
        ports:
        - containerPort: 5000
status: {}

