apiVersion: v1
kind: Pod                                            # specifies the kind of the Kubernetes Resource that we want to create. In our case, a Pod.
metadata:
  name: frontend
  labels:
    app: frontend                                    # defines the name for the resource. We named it sa-frontend.
spec:                                                # is the object that defines the desired state for the resource. The most important property of a Pods Spec is the Array of containers.
  containers:
    - image: santagar/kubernetes-solution-frontend   # is the container image we want to start in this pod.
      name: frontend                                 # is the unique name for a container in a pod.
      ports:
        - containerPort: 80                          # is the port at which the container is listening. This is just an indicator for the reader (dropping the port doesn’t restrict access).
