apiVersion: v1
kind: Pod
metadata:
  name: frontend-2
  labels:
    app: frontend
spec:
  containers:
    - image: santagar/kubernetes-solution-frontend
      name: frontend
      ports:
        - containerPort: 80
